//
// Created by andi on 28.04.23.
//

#ifndef LEARNINGPROJECT_LATTICEFOURIERTRANSFORM_H
#define LEARNINGPROJECT_LATTICEFOURIERTRANSFORM_H


class LatticeFourierTransform {

};


#endif //LEARNINGPROJECT_LATTICEFOURIERTRANSFORM_H
