//
// Created by andi on 18.04.23.
//

#ifndef LEARNINGPROJECT_CONVERGENCECHECKDIFFUSION_H
#define LEARNINGPROJECT_CONVERGENCECHECKDIFFUSION_H


class ConvergenceCheckDiffusion {

};


#endif //LEARNINGPROJECT_CONVERGENCECHECKDIFFUSION_H
