//
// Created by andi on 28.07.23.
//

#ifndef LEARNINGPROJECT_ORIGINALBINDERCUMULANT_H
#define LEARNINGPROJECT_ORIGINALBINDERCUMULANT_H


class OriginalBinderCumulant {

};


#endif //LEARNINGPROJECT_ORIGINALBINDERCUMULANT_H
